parameters:
  - name: azureSubscription
    type: string
  - name: containerAppName
    type: string
  - name: resourceGroup
    type: string
  - name: containerRegistry
    type: string
  - name: repository
    type: string
  - name: acrImageTag
    type: string
  - name: slackWebhookUrl
    type: string
  - name: acrServiceConnection
    type: string

trigger:
  - none  # No trigger for the template itself

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm --version
    npm install
    npm run build
    ls -la
    ls build
  displayName: 'Install and Build'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: ${{ parameters.acrServiceConnection }}

- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: ${{ parameters.repository }}
    tags: |
      ${{ parameters.acrImageTag }}

# Azure CLI login
- task: AzureCLI@2
  displayName: 'Azure CLI Login'
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'

# Deploy to Azure Container Apps
- task: AzureContainerApps@1
  displayName: "Deploy to Azure Container Apps"
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    containerAppName: ${{ parameters.containerAppName }}
    resourceGroup: ${{ parameters.resourceGroup }}
    imageToDeploy: '${{ parameters.containerRegistry }}/${{ parameters.repository }}:${{ parameters.acrImageTag }}'

# Send Slack notification
- script: |
    COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
    COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
    echo $COMMIT_MESSAGE
    curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"Deploy To CLIENT FE DEV\",
          \"attachments\": [
            {
              \"fallback\": \"Commit Details\",
              \"text\":  \"This commit Triggered by: ${COMMIT_AUTHOR}\",
              \"fields\": [
                {
                  \"title\": \"Commit URL\",
                  \"value\": \"<https://github.com/webatts/p2p-payments-fe/commit/$(Build.SourceVersion)|Click here for commit details>\" 
                },
                {
                  \"title\": \"Commit Details\",
                  \"value\": \"<https://github.com/webatts/p2p-payments-fe/commit/$(Build.SourceVersion)|${COMMIT_MESSAGE}>\" 
                },
                {
                  \"title\": \"Commit Author\",
                  \"value\": \"${COMMIT_AUTHOR}\" 
                },
                {
                  \"title\": \"Target Application\",
                  \"value\": \"<https://devclient.inzo.co/|Click here to INZO-CLIENT>\" 
                }
              ]
            }
          ]
        }" ${{ parameters.slackWebhookUrl }}
  displayName: 'Send Slack Notification'
