parameters:
  - name: appName
    type: string
  - name: containerName
    type: string
  - name: resourceGroup
    type: string
  - name: acrName
    type: string
  - name: serviceConnection
    type: string
  - name: dockerFilePath
    type: string
  - name: repoName
    type: string

trigger: none

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: '--settings settings.xml --global-settings settings.xml package'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: ${{ parameters.acrName }}

  - script: |
      echo Starting the build action
      ls target/
      cp target/${{ parameters.appName }}-0.0.1-SNAPSHOT.jar docker/develop
    displayName: 'Prepare Build Artifacts'

  - task: Docker@2
    displayName: Build and Push Image
    inputs:
      command: buildAndPush
      dockerfile: ${{ parameters.dockerFilePath }}
      repository: ${{ parameters.repoName }}
      tags: |
        $(Build.SourceBranchName)-$(Build.SourceVersion)

  - task: AzureCLI@2
    displayName: 'Azure CLI Login'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az account show'

  - task: AzureContainerApps@1
    displayName: Deploy to Azure Container Apps
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      containerAppName: ${{ parameters.containerName }}
      resourceGroup: ${{ parameters.resourceGroup }}
      imageToDeploy: '${{ parameters.acrName }}.azurecr.io/${{ parameters.repoName }}:$(Build.SourceBranchName)-$(Build.SourceVersion)'

  - script: |
      echo Sending Slack Notification
      COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
      COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
      curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"Deploy To HUB BE\",
            \"attachments\": [
              {
                \"fallback\": \"Commit Details\",
                \"text\": \"This commit Triggered by: ${COMMIT_AUTHOR}\",
                \"fields\": [
                  {
                    \"title\": \"Commit URL\",
                    \"value\": \"<https://github.com/webatts/hub-be/commit/$(Build.SourceVersion)|Click here for commit details>\"
                  },
                  {
                    \"title\": \"Commit Details\",
                    \"value\": \"<https://github.com/webatts/hub-be/commit/$(Build.SourceVersion)|${COMMIT_MESSAGE}>\"
                  },
                  {
                    \"title\": \"Commit Author\",
                    \"value\": \"${COMMIT_AUTHOR}\"
                  },
                  {
                    \"title\": \"Target Application\",
                    \"value\": \"<https://hubdev-be.bravestone-66be93d4.uksouth.azurecontainerapps.io/|Click here to INZO-DEV-BE>\"
                  },
                  {
                    \"title\": \"API URLs\",
                    \"value\": \"<https://hubdev-be.bravestone-66be93d4.uksouth.azurecontainerapps.io/swagger-ui/index.html|Click here to INZO-SWAGGER-UI>\"
                  }
                ]
              }
            ]
          }" https://hooks.slack.com/services/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
    displayName: 'Send Slack Notification'
